### ISSUE TITLE
Autocompletion for notes not triggered in maximized mode

### ISSUE THREAD

**Issue by ivan-lednev** [Razumihin/obsidian-fullscreen-plugin#1]
# Steps to reproduce

- Open a note in maximized mode
- Type [[

# Expected

- Autocompletion pop-up is triggered

# Actual

- No autocompletion pop-up is triggered

**Comment by Razumihin** [comment]
I have to check if I can do anything to that. I have used this plugin mainly in reader mode so I haven't noticed it. As the plugin's operation is currently super simple, I have to dig what does it call under the obsidian leaf based layout model to see if it's fixable.

**Comment by zzdcgg** [comment]
Same problem here...

**Comment by gala8y** [comment]
Hello, I think this is a more general problem with all Obsidian pop-ups - as the window gets to the top, nothing gets higher than the window. Its a 'z-depth' issue, so to speak.
