### ISSUE TITLE
Add a class to body when fullscreen

### ISSUE THREAD

**Issue by lightlii** [Razumihin/obsidian-fullscreen-plugin#8]
Would be great if a classname would be added to the body element when the user activates fullscreen so themes could make best use of the plugin (eg. hiding the title bar when fullscreeen)

Happy to make a PR for this if you think it's a worthwhile feature, should be straightforward enough.

**Comment by Razumihin** [comment]
Hi, yeah sounds like a useful feature. If you'll make a PR I can check and merge it.
