### ISSUE TITLE
 Empty space between active panel and right panels upon return to normal view

### ISSUE THREAD

**Issue by Aldrichyl** [Razumihin/obsidian-fullscreen-plugin#9]
![image](https://user-images.githubusercontent.com/62477821/147385605-f7fe3d25-2177-4b84-b213-c67a6be87a23.png)
Hey ! This plugin is amazing and I love it but I've noticed that whenever I click "Esc" to return back to the normal view, a black (empty) rectangle appear at right of the pane, and the only way to remove it is to always readjust the line separating the right panels with the active one.
Is there a solution to this problem ? Or is it because of the "Sliding Panels" plugin ? 
Thank you !

**Comment by Razumihin** [comment]
I'm not exactly sure why, but it seems to do that on the Sliding panels plugin, yeah. I think it might be CSS related.

**Comment by Aldrichyl** [comment]
Oh so it's because of the Sliding Panes ? I've tried again without it and it actually works so it must be related to the community plugin.
